/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.24).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.GetItemsByUserIdsResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-12-01T02:18:22.352Z")

@Validated
@Api(value = "item", description = "the item API")
@RequestMapping(value = "")
public interface ItemApi {

    @ApiOperation(value = "Finds items", nickname = "getItemsByUserIds", notes = "Multiple status values can be provided with comma separated strings", response = GetItemsByUserIdsResponse.class, responseContainer = "List", tags={ "item", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = GetItemsByUserIdsResponse.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid UserIds value") })
    @RequestMapping(value = "/item",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<GetItemsByUserIdsResponse>> getItemsByUserIds(@NotNull @ApiParam(value = "Items posted by given userIds will be retrieved", required = true) @Valid @RequestParam(value = "userIds", required = true) List<String> userIds);

}
